# Generated by Django 4.1.7 on 2025-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labscenario',
            name='valid_commands_map',
        ),
        migrations.RemoveField(
            model_name='userlabsession',
            name='command_history',
        ),
        migrations.RemoveField(
            model_name='userlabsession',
            name='current_context',
        ),
        migrations.AddField(
            model_name='labscenario',
            name='allowed_devices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userlabsession',
            name='current_device',
            field=models.CharField(default='R1', max_length=10),
        ),
    ]
