# Generated by Django 4.1.7 on 2025-11-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_labscenario_valid_commands_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labscenario',
            name='reward_money',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='labscenario',
            name='reward_xp',
            field=models.IntegerField(default=10),
        ),
    ]
