# Generated by Django 4.1.7 on 2025-11-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_labscenario_reward_money_labscenario_reward_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='labscenario',
            name='min_level',
            field=models.IntegerField(default=1),
        ),
    ]
