# Generated by Django 4.1.7 on 2025-11-22 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='NetStart Inc.', max_length=100)),
                ('skin_color', models.CharField(default='#f5d0b0', max_length=20)),
                ('hair_style', models.IntegerField(default=1)),
                ('hair_color', models.CharField(default='#4a3b2a', max_length=20)),
                ('shirt_color', models.CharField(default='#3498db', max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=1000)),
                ('day', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
